/* Extracted from the user-provided DOCX; statuses are preliminary review findings. */
export const sourceEntries = [
  {
    "id": "ref-01",
    "number": 1,
    "category": "sources",
    "title": "中共中央关于党的百年奋斗重大成就和历史经验的决议",
    "author": "中共中央",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "中共中央",
      "EB/OL",
      "官方镜像可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 9 处 · 官方镜像可核",
    "body": "原 gov.cn 地址被检索工具拒绝；司法部转载可核对标题与全文。",
    "url": "https://www.gov.cn/zhengce/2021-11/16/content_5651269.htm",
    "alternativeUrl": "https://www.moj.gov.cn/pub/sfbgw/zwgkztzl/2021nzt/xxgclzqh2021/tt_2603/202111/t20211122_442268.html",
    "verified": "官方镜像可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中共中央. 中共中央关于党的百年奋斗重大成就和历史经验的决议[EB/OL]. (2021-11-16)[2026-09-26]. https://www.gov.cn/zhengce/2021-11/16/content_5651269.htm.",
    "citedParagraphs": [
      4,
      10,
      39,
      107,
      173,
      175,
      177,
      200,
      213
    ],
    "citationCount": 9
  },
  {
    "id": "ref-02",
    "number": 2,
    "category": "sources",
    "title": "毛泽东思想和中国特色社会主义理论体系概论（2023年版）",
    "author": "本书编写组",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "理论关系与经典文献",
    "keywords": [
      "本书编写组",
      "M",
      "出版社书目可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 15 处 · 出版社书目可核",
    "body": "高等教育出版社产品页可核题名、作者、年份；正文所用具体页码仍需补充。",
    "url": null,
    "alternativeUrl": "https://xuanshu.hep.com.cn/front/h5Mobile/bookDetails?bookId=63cac918938b7cc2960ef83f",
    "verified": "出版社书目可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "本书编写组. 毛泽东思想和中国特色社会主义理论体系概论（2023年版）[M]. 北京: 高等教育出版社, 2023.",
    "citedParagraphs": [
      4,
      5,
      6,
      10,
      11,
      16,
      18,
      37,
      38,
      39,
      89,
      123,
      157,
      200,
      213
    ],
    "citationCount": 15
  },
  {
    "id": "ref-03",
    "number": 3,
    "category": "sources",
    "title": "毛泽东思想与中国特色社会主义理论体系的关系",
    "author": "王伟光",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "王伟光",
      "EB/OL",
      "原页可核·作者著录错误",
      "引文需改"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 原页可核·作者著录错误",
    "body": "原尾注精确网址可读取，网页署名徐光春，题为《毛泽东思想与中国特色社会主义理论体系的关系》，刊于2013年9月16日；尾注列王伟光错误。正文第7段直接引语近似王伟光2012年采访报道，但“的老祖宗”等词与报道原话不符，须重校并另引。",
    "url": "http://theory.people.com.cn/n/2013/0916/c40531-22931166.html",
    "alternativeUrl": "https://cpc.people.com.cn/n/2012/1109/c350000-19536460.html",
    "verified": "原页可核·作者著录错误",
    "claimStatus": "引文需改",
    "claimNote": "第7段的直接引语与王伟光2012年报道不完全相同；删去原报道没有的“的老祖宗”，按原话校正，并改引王伟光报道。",
    "bibliography": "王伟光. 毛泽东思想与中国特色社会主义理论体系的关系[EB/OL]. (2013-09-16)[2026-09-26]. http://theory.people.com.cn/n/2013/0916/c40531-22931166.html.",
    "citedParagraphs": [
      7
    ],
    "citationCount": 1
  },
  {
    "id": "ref-04",
    "number": 4,
    "category": "sources",
    "title": "马克思主义中国化的三次飞跃是？",
    "author": "共产党员网",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "共产党员网",
      "EB/OL",
      "归属与链接错配",
      "归属错误"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 归属与链接错配",
    "body": "正文四分法“一根相连、一脉相承、一体相依、一帜相随”见徐光春2013年文章；原尾注的网友问答不能证明曲青山署名。",
    "url": "https://wenda.12371.cn/liebiao.php?mod=viewthread&tid=634347",
    "alternativeUrl": "https://news.12371.cn/2013/09/16/ARTI1379294852083677.shtml",
    "verified": "归属与链接错配",
    "claimStatus": "归属错误",
    "claimNote": "第9段四分法对应徐光春文章，不能据现有来源写作曲青山的总结。",
    "bibliography": "共产党员网. 马克思主义中国化的三次飞跃是？[EB/OL]. [2026-09-26]. https://wenda.12371.cn/liebiao.php?mod=viewthread&tid=634347.",
    "citedParagraphs": [
      9
    ],
    "citationCount": 1
  },
  {
    "id": "ref-05",
    "number": 5,
    "category": "sources",
    "title": "关于坚持和发展中国特色社会主义的几个问题",
    "author": "习近平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "习近平",
      "EB/OL",
      "原页可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 2 处 · 原页可核",
    "body": "求是网页作者与标题一致。",
    "url": "https://www.qstheory.cn/dukan/qs/2019-03/31/c_1124302776.htm",
    "alternativeUrl": null,
    "verified": "原页可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "习近平. 关于坚持和发展中国特色社会主义的几个问题[EB/OL]. (2019-03-31)[2026-09-26]. https://www.qstheory.cn/dukan/qs/2019-03/31/c_1124302776.htm.",
    "citedParagraphs": [
      12,
      196
    ],
    "citationCount": 2
  },
  {
    "id": "ref-06",
    "number": 6,
    "category": "sources",
    "title": "中国共产党的一百年",
    "author": "中共中央党史和文献研究院",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "理论关系与经典文献",
    "keywords": [
      "中共中央党史和文献研究院",
      "M",
      "出版信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 12 处 · 出版信息可核",
    "body": "中央党史和文献研究院官网证实该书由中共党史出版社于2022年出版；具体引用页码待补。",
    "url": null,
    "alternativeUrl": "https://www.dswxyjy.org.cn/n1/2022/0719/c434085-32479348.html",
    "verified": "出版信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中共中央党史和文献研究院. 中国共产党的一百年[M]. 北京: 中共党史出版社, 2022.",
    "citedParagraphs": [
      18,
      24,
      25,
      28,
      38,
      49,
      67,
      102,
      114,
      118,
      123,
      159
    ],
    "citationCount": 12
  },
  {
    "id": "ref-07",
    "number": 7,
    "category": "sources",
    "title": "“一五”计划（1953—1957年）",
    "author": "国家发展和改革委员会",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "革命与社会主义建设",
    "keywords": [
      "国家发展和改革委员会",
      "EB/OL",
      "原页可核·论据待补",
      "论据不足"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 原页可核·论据待补",
    "body": "国家发改委 PDF 是“一五”计划原件；不能单凭计划原件证明正文所述1957年完成情况和19.6%增速。",
    "url": "https://www.ndrc.gov.cn/fggz/fzzlgh/gjfzgh/202112/P020211214370085847910.pdf",
    "alternativeUrl": null,
    "verified": "原页可核·论据待补",
    "claimStatus": "论据不足",
    "claimNote": "第28段的1957年完成数字与增速，不能仅由计划原件推出。",
    "bibliography": "国家发展和改革委员会. “一五”计划（1953—1957年）[EB/OL]. (2021-12-14)[2026-09-26]. https://www.ndrc.gov.cn/fggz/fzzlgh/gjfzgh/202112/P020211214370085847910.pdf.",
    "citedParagraphs": [
      28
    ],
    "citationCount": 1
  },
  {
    "id": "ref-08",
    "number": 8,
    "category": "sources",
    "title": "中国农村的社会主义高潮",
    "author": "毛泽东",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "革命与社会主义建设",
    "keywords": [
      "毛泽东",
      "M",
      "编著责任需更正",
      "编著责任待改"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 编著责任需更正",
    "body": "该书是农业合作化材料汇编，1956年出版报道署中共中央办公厅编辑；毛泽东撰写序言、批注，不宜仅以“毛泽东”作整书作者。",
    "url": null,
    "alternativeUrl": "https://www.theorychina.org.cn/c/2019-07-15/1270108.shtml",
    "verified": "编著责任需更正",
    "claimStatus": "编著责任待改",
    "claimNote": "第31段可进一步定位毛泽东所作按语；整部汇编的作者著录需核定。",
    "bibliography": "毛泽东. 中国农村的社会主义高潮[M]. 北京: 人民出版社, 1956.",
    "citedParagraphs": [
      31
    ],
    "citationCount": 1
  },
  {
    "id": "ref-09",
    "number": 9,
    "category": "sources",
    "title": "红旗渠精神｜红旗渠：让太行山低头的“人工天河”",
    "author": "河南省文化和旅游厅",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "革命与社会主义建设",
    "keywords": [
      "河南省文化和旅游厅",
      "EB/OL",
      "正文论据需另引",
      "需另引具体文章"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 正文论据需另引",
    "body": "原河南文旅页可读取，为红旗渠概览；正文第34段的“四摸”及“境内寻水”论述不在该页，可在《学习时报》文章的上观新闻转载页逐句核对。",
    "url": "https://hct.henan.gov.cn/2023/02-22/2693666.html",
    "alternativeUrl": "https://www.jfdaily.com/wx/detail.do?id=611679",
    "verified": "正文论据需另引",
    "claimStatus": "需另引具体文章",
    "claimNote": "第34段的“四摸”及工程设计论述有更贴合的《学习时报》文章转载页。",
    "bibliography": "河南省文化和旅游厅. 红旗渠精神｜红旗渠：让太行山低头的“人工天河”[EB/OL]. (2023-02-22)[2026-09-26]. https://hct.henan.gov.cn/2023/02-22/2693666.html.",
    "citedParagraphs": [
      34
    ],
    "citationCount": 1
  },
  {
    "id": "ref-10",
    "number": 10,
    "category": "sources",
    "title": "走进小岗",
    "author": "中国小岗村",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "中国小岗村",
      "EB/OL",
      "原页可核·细节待核",
      "细节待核"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 5 处 · 原页可核·细节待核",
    "body": "所列小岗村网址可读取，为小岗村概览及大事记；正文所引具体数字和原话仍需逐项复核。",
    "url": "http://www.cnxiaogang.com/about/",
    "alternativeUrl": "https://xgly.cnxiaogang.com/info.php?class_id=101",
    "verified": "原页可核·细节待核",
    "claimStatus": "细节待核",
    "claimNote": "第42—46段引用同一概览页，数字及直接引语需找到各自出处。",
    "bibliography": "中国小岗村. 走进小岗[EB/OL]. [2026-09-26]. http://www.cnxiaogang.com/about/.",
    "citedParagraphs": [
      42,
      43,
      44,
      45,
      46
    ],
    "citationCount": 5
  },
  {
    "id": "ref-11",
    "number": 11,
    "category": "sources",
    "title": "深圳市2024年国民经济和社会发展统计公报",
    "author": "深圳市统计局, 国家统计局深圳调查队",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "深圳市统计局, 国家统计局深圳调查队",
      "EB/OL",
      "原页可核·论据需分引",
      "部分支持"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 2 处 · 原页可核·论据需分引",
    "body": "2024年统计公报可支持当年GDP 36801.87亿元及战略性新兴产业占比42.3%；第51段的2020—2024年均增速、单位面积产出及能耗比较不在所引公报中，应补引新华社2025年深圳特区45周年报道。第52段“约1.56万亿元”可由公报占比推算，但应注明推算或补明示来源。",
    "url": "https://www.sz.gov.cn/cn/xxgk/zfxxgj/tjsj/tjgb/content/post_12190855.html",
    "alternativeUrl": "https://yjgl.sz.gov.cn/zwgk/xxgkml/qt/yjyw/content/post_12347124.html",
    "verified": "原页可核·论据需分引",
    "claimStatus": "部分支持",
    "claimNote": "第51段多项比较指标不在所列公报；第52段1.56万亿元应补明示来源或注明由占比推算。",
    "bibliography": "深圳市统计局, 国家统计局深圳调查队. 深圳市2024年国民经济和社会发展统计公报[EB/OL]. (2025-05-22)[2026-09-26]. https://www.sz.gov.cn/cn/xxgk/zfxxgj/tjsj/tjgb/content/post_12190855.html.",
    "citedParagraphs": [
      51,
      52
    ],
    "citationCount": 2
  },
  {
    "id": "ref-12",
    "number": 12,
    "category": "sources",
    "title": "2025年政府工作报告",
    "author": "深圳市人民政府",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "深圳市人民政府",
      "EB/OL",
      "原页可核·统计时点混用",
      "统计时点混用"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 原页可核·统计时点混用",
    "body": "2025年深圳政府工作报告可核国家高新技术企业超2.5万家及“小巨人”1025家等；该报告所述2024年经营主体约440.4万家，不是正文的450.8万家。450.8万家来自较晚报道；深圳官方另有截至2025年6月底450.8万户的口径，应标明统计时点。1.1万家专精特新企业及1.56万亿元亦应另行补证。",
    "url": "https://www.sz.gov.cn/zfgb/2025/1366/content/post_12089947.html",
    "alternativeUrl": "https://yjgl.sz.gov.cn/zwgk/xxgkml/qt/yjyw/content/post_12347124.html",
    "verified": "原页可核·统计时点混用",
    "claimStatus": "统计时点混用",
    "claimNote": "第53段450.8万家不能归于2025年政府工作报告；报告记载2024年约440.4万家。",
    "bibliography": "深圳市人民政府. 2025年政府工作报告[EB/OL]. (2025-03-24)[2026-09-26]. https://www.sz.gov.cn/zfgb/2025/1366/content/post_12089947.html.",
    "citedParagraphs": [
      53
    ],
    "citationCount": 1
  },
  {
    "id": "ref-13",
    "number": 13,
    "category": "sources",
    "title": "2025年义乌市国民经济和社会发展统计公报",
    "author": "义乌市统计局",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "义乌市统计局",
      "EB/OL",
      "原页附件全文已取得",
      "公报全文已取得·待逐项核"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 3 处 · 原页附件全文已取得",
    "body": "义乌市政府原尾注页面可读取，所附2025年统计公报DOCX全文已取得；页面署义乌市统计局、国家统计局义乌调查队。公报可核对8364.87亿元、收入倍差1.76等数值，正文具体统计表述仍需逐项比对。",
    "url": "http://www.yw.gov.cn/col/col1229187192/art/2026/art_ada37ae526d54f72a4c0ec6e092d5072.html",
    "alternativeUrl": "https://zjic.zj.gov.cn/ywdh/qyfz/202607/t20260713_24154880.shtml",
    "verified": "原页附件全文已取得",
    "claimStatus": "公报全文已取得·待逐项核",
    "claimNote": "第56—58段所引公报附件全文已取得，能够直接核对若干数值；仍需逐项比对正文的统计时点与表述。",
    "bibliography": "义乌市统计局. 2025年义乌市国民经济和社会发展统计公报[EB/OL]. (2026-05-21)[2026-09-26]. http://www.yw.gov.cn/col/col1229187192/art/2026/art_ada37ae526d54f72a4c0ec6e092d5072.html.",
    "citedParagraphs": [
      56,
      57,
      58
    ],
    "citationCount": 3
  },
  {
    "id": "ref-14",
    "number": 14,
    "category": "sources",
    "title": "邓小平文选: 第三卷",
    "author": "邓小平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "理论关系与经典文献",
    "keywords": [
      "邓小平",
      "M",
      "版本信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 6 处 · 版本信息可核",
    "body": "理论中国网收录《邓小平文选》第三卷并标注人民出版社1993年版；具体页码待补。",
    "url": null,
    "alternativeUrl": "https://www.theorychina.org.cn/llzgxs/lxzz_894/dxp/",
    "verified": "版本信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "邓小平. 邓小平文选: 第三卷[M]. 北京: 人民出版社, 1993.",
    "citedParagraphs": [
      65,
      66,
      67,
      104,
      116,
      135
    ],
    "citationCount": 6
  },
  {
    "id": "ref-15",
    "number": 15,
    "category": "sources",
    "title": "毛泽东选集: 第一卷",
    "author": "毛泽东",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "理论关系与经典文献",
    "keywords": [
      "毛泽东",
      "M",
      "版本信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 3 处 · 版本信息可核",
    "body": "理论中国网列《毛泽东选集》第一卷为人民出版社1991年版；具体页码待补。",
    "url": null,
    "alternativeUrl": "https://www.theorychina.org.cn/llzgxs/lxzz_894/",
    "verified": "版本信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "毛泽东. 毛泽东选集: 第一卷[M]. 北京: 人民出版社, 1991.",
    "citedParagraphs": [
      78,
      80,
      102
    ],
    "citationCount": 3
  },
  {
    "id": "ref-16",
    "number": 16,
    "category": "sources",
    "title": "邓小平文选: 第二卷",
    "author": "邓小平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "理论关系与经典文献",
    "keywords": [
      "邓小平",
      "M",
      "版本信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 4 处 · 版本信息可核",
    "body": "理论中国网列《邓小平文选》第二卷为人民出版社1994年版；具体页码待补。",
    "url": null,
    "alternativeUrl": "https://www.theorychina.org.cn/llzgxs/lxzz_894/dxp/",
    "verified": "版本信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "邓小平. 邓小平文选: 第二卷[M]. 北京: 人民出版社, 1994.",
    "citedParagraphs": [
      82,
      83,
      93,
      186
    ],
    "citationCount": 4
  },
  {
    "id": "ref-17",
    "number": 17,
    "category": "sources",
    "title": "在纪念毛泽东同志诞辰120周年座谈会上的讲话",
    "author": "习近平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "A",
    "theme": "理论关系与经典文献",
    "keywords": [
      "习近平",
      "A",
      "所收篇章待核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 所收篇章待核",
    "body": "讲话原文可在人民网核对；《习近平谈治国理政》第一卷所收相关节选的篇名与整篇讲话著录关系需核定。",
    "url": null,
    "alternativeUrl": "https://theory.people.com.cn/n/2013/1227/c40531-23954508.html",
    "verified": "所收篇章待核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "习近平. 在纪念毛泽东同志诞辰120周年座谈会上的讲话[A]//习近平谈治国理政. 北京: 外文出版社, 2014.",
    "citedParagraphs": [
      85
    ],
    "citationCount": 1
  },
  {
    "id": "ref-18",
    "number": 18,
    "category": "sources",
    "title": "邓小平年谱（1904—1974）: 下卷",
    "author": "中共中央文献研究室",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "革命与社会主义建设",
    "keywords": [
      "中共中央文献研究室",
      "M",
      "书目可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 书目可核",
    "body": "中央文献出版社2009年版下卷可由图书目录核对；具体引用页码待补。",
    "url": null,
    "alternativeUrl": "https://www.12371.cn/2020/07/06/ARTI1594003482037741.shtml",
    "verified": "书目可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中共中央文献研究室. 邓小平年谱（1904—1974）: 下卷[M]. 北京: 中央文献出版社, 2009.",
    "citedParagraphs": [
      87
    ],
    "citationCount": 1
  },
  {
    "id": "ref-19",
    "number": 19,
    "category": "sources",
    "title": "论联合政府",
    "author": "毛泽东",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "A",
    "theme": "理论关系与经典文献",
    "keywords": [
      "毛泽东",
      "A",
      "篇章可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 篇章可核",
    "body": "理论中国网在线《毛泽东选集》第三卷可查《论联合政府》正文；引用页码待补。",
    "url": null,
    "alternativeUrl": "https://ebook.theorychina.org.cn/ebook/upload/storage/files/2022/07/26/96241bf235bd68bad86fed6360e6a8bc32635/files/basic-html/page251.html",
    "verified": "篇章可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "毛泽东. 论联合政府[A]//毛泽东选集: 第三卷. 北京: 人民出版社, 1991.",
    "citedParagraphs": [
      91
    ],
    "citationCount": 1
  },
  {
    "id": "ref-20",
    "number": 20,
    "category": "sources",
    "title": "高举中国特色社会主义伟大旗帜 为全面建设社会主义现代化国家而团结奋斗——在中国共产党第二十次全国代表大会上的报告",
    "author": "习近平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "习近平",
      "EB/OL",
      "官方镜像可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 2 处 · 官方镜像可核",
    "body": "原 gov.cn 地址被检索工具拒绝；共产党员网文件专题和政府站 PDF 可核标题。",
    "url": "https://www.gov.cn/xinwen/2022-10/25/content_5721685.htm",
    "alternativeUrl": "https://www.12371.cn/special/xg20djs/wj/",
    "verified": "官方镜像可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "习近平. 高举中国特色社会主义伟大旗帜 为全面建设社会主义现代化国家而团结奋斗——在中国共产党第二十次全国代表大会上的报告[EB/OL]. (2022-10-25)[2026-09-26]. https://www.gov.cn/xinwen/2022-10/25/content_5721685.htm.",
    "citedParagraphs": [
      89,
      96
    ],
    "citationCount": 2
  },
  {
    "id": "ref-21",
    "number": 21,
    "category": "sources",
    "title": "毛泽东年谱（1893—1949）: 上卷",
    "author": "中共中央文献研究室",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "革命与社会主义建设",
    "keywords": [
      "中共中央文献研究室",
      "M",
      "版本信息需补",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 版本信息需补",
    "body": "中央党史和文献研究院记载2013年为修订本；尾注未标“修订本”，具体页码待补。",
    "url": null,
    "alternativeUrl": "https://www.dswxyjy.org.cn/n1/2024/0401/c423725-40207890.html",
    "verified": "版本信息需补",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中共中央文献研究室. 毛泽东年谱（1893—1949）: 上卷[M]. 北京: 中央文献出版社, 2013.",
    "citedParagraphs": [
      99
    ],
    "citationCount": 1
  },
  {
    "id": "ref-22",
    "number": 22,
    "category": "sources",
    "title": "坚持和运用好毛泽东思想活的灵魂",
    "author": "《红旗文稿》编辑部",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "《红旗文稿》编辑部",
      "EB/OL",
      "署名需更正",
      "作者著录错误"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 署名需更正",
    "body": "求是网页署名为牛先锋，文档列为《红旗文稿》编辑部。",
    "url": "https://www.qstheory.cn/dukan/hqwg/2024-01/16/c_1130060795.htm",
    "alternativeUrl": null,
    "verified": "署名需更正",
    "claimStatus": "作者著录错误",
    "claimNote": "第101段来源网页署名牛先锋，原尾注著录为编辑部。",
    "bibliography": "《红旗文稿》编辑部. 坚持和运用好毛泽东思想活的灵魂[EB/OL]. (2024-01-16)[2026-09-26]. https://www.qstheory.cn/dukan/hqwg/2024-01/16/c_1130060795.htm.",
    "citedParagraphs": [
      101
    ],
    "citationCount": 1
  },
  {
    "id": "ref-23",
    "number": 23,
    "category": "sources",
    "title": "改革开放的最前端——蛇口",
    "author": "新华社",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "新华社",
      "EB/OL",
      "原页可核·署名日期错配",
      "引文来源错配"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 2 处 · 原页可核·署名日期错配",
    "body": "原尾注搜狐页面实际账号署名“土生土长深圳人”，页面日期为2017-12-26，并称综合自深圳地名网、网络；并非尾注所列“新华社、2017-12-28”。正文第120段奖励制度可参照招商局历史博物馆“四分钱的故事”，其中有超额每车4分钱、最高131车，但未证实“每天定额40车”。",
    "url": "https://www.sohu.com/a/212908333_99950450",
    "alternativeUrl": "https://1872.cmhk.com/baike/2611.html",
    "verified": "原页可核·署名日期错配",
    "claimStatus": "引文来源错配",
    "claimNote": "原搜狐页面不是所列新华社署名，且未载“四分钱”制度；第120段的超额每车4分钱、最高131车须改引招商局史料，“定额40车”仍无直接证据。",
    "bibliography": "新华社. 改革开放的最前端——蛇口[EB/OL]. (2017-12-28)[2026-09-26]. https://www.sohu.com/a/212908333_99950450.",
    "citedParagraphs": [
      120,
      169
    ],
    "citationCount": 2
  },
  {
    "id": "ref-24",
    "number": 24,
    "category": "sources",
    "title": "毛泽东与我国社会主义基本制度的确立",
    "author": "沙健孙",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "革命与社会主义建设",
    "keywords": [
      "沙健孙",
      "EB/OL",
      "站内跳转后原文可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 2 处 · 站内跳转后原文可核",
    "body": "北京大学新闻网原尾注旧网址返回站内 JavaScript 跳转；跳转到新地址后可读取沙健孙同题文章全文。",
    "url": "https://news.pku.edu.cn/ztrd/jnmzddc120zn/4683-280081.htm",
    "alternativeUrl": "http://news.pku.edu.cn/info/5771/781901.htm",
    "verified": "站内跳转后原文可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "沙健孙. 毛泽东与我国社会主义基本制度的确立[EB/OL]. [2026-09-26]. https://news.pku.edu.cn/ztrd/jnmzddc120zn/4683-280081.htm.",
    "citedParagraphs": [
      28,
      173
    ],
    "citationCount": 2
  },
  {
    "id": "ref-25",
    "number": 25,
    "category": "sources",
    "title": "对起草《关于建国以来党的若干历史问题的决议》的意见",
    "author": "邓小平",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "邓小平",
      "EB/OL",
      "历史日期需更正",
      "日期需改"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 历史日期需更正",
    "body": "理论中国网明确该篇系1980年3月至1981年6月多次谈话的节录，原尾注单写1980-03-01会误导为单次讲话；网页发布日期亦应与谈话时段分开。",
    "url": "http://www.reformdata.org/1980/0301/5185.shtml",
    "alternativeUrl": "https://www.theorychina.org.cn/c/1981-06-22/1489329.shtml",
    "verified": "历史日期需更正",
    "claimStatus": "日期需改",
    "claimNote": "第186段引语所属材料跨1980年3月至1981年6月多次谈话。",
    "bibliography": "邓小平. 对起草《关于建国以来党的若干历史问题的决议》的意见[EB/OL]. (1980-03-01)[2026-09-26]. http://www.reformdata.org/1980/0301/5185.shtml.",
    "citedParagraphs": [
      186
    ],
    "citationCount": 1
  },
  {
    "id": "ref-26",
    "number": 26,
    "category": "sources",
    "title": "关于建国以来党的若干历史问题的决议",
    "author": "中国共产党中央委员会",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "理论关系与经典文献",
    "keywords": [
      "中国共产党中央委员会",
      "EB/OL",
      "原页可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 原页可核",
    "body": "共产党员网转载决议全文；历史通过日期与网页转载日期应区分。",
    "url": "https://www.12371.cn/2021/11/09/ARTI1636454249781129.shtml",
    "alternativeUrl": null,
    "verified": "原页可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中国共产党中央委员会. 关于建国以来党的若干历史问题的决议[EB/OL]. (1981-06-27)[2026-09-26]. https://www.12371.cn/2021/11/09/ARTI1636454249781129.shtml.",
    "citedParagraphs": [
      188
    ],
    "citationCount": 1
  },
  {
    "id": "ref-27",
    "number": 27,
    "category": "sources",
    "title": "红色亿元村——南街村",
    "author": "南街村官方网站",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "EB/OL",
    "theme": "改革开放与地方实践",
    "keywords": [
      "南街村官方网站",
      "EB/OL",
      "主页不足以支撑细节",
      "数字待核"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 主页不足以支撑细节",
    "body": "尾注指向南街村主页，未能据此核对正文的26家企业与25亿元等具体表述。",
    "url": "http://www.nanjiecun.cn/",
    "alternativeUrl": "https://www.nanjiecun.cn/homepage.asp",
    "verified": "主页不足以支撑细节",
    "claimStatus": "数字待核",
    "claimNote": "第197段的具体企业数量和产值不能用网站首页证明。",
    "bibliography": "南街村官方网站. 红色亿元村——南街村[EB/OL]. [2026-09-26]. http://www.nanjiecun.cn/.",
    "citedParagraphs": [
      197
    ],
    "citationCount": 1
  },
  {
    "id": "ref-28",
    "number": 28,
    "category": "sources",
    "title": "习近平的七年知青岁月",
    "author": "中央党校采访实录编辑室",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "人物经历",
    "keywords": [
      "中央党校采访实录编辑室",
      "M",
      "出版信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 出版信息可核",
    "body": "共产党员网转新华社消息可核该书由中共中央党校出版社于2017年出版；具体页码待补。",
    "url": null,
    "alternativeUrl": "https://fuwu.12371.cn/2017/08/17/ARTI1502970112550606.shtml",
    "verified": "出版信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中央党校采访实录编辑室. 习近平的七年知青岁月[M]. 北京: 中共中央党校出版社, 2017.",
    "citedParagraphs": [
      224
    ],
    "citationCount": 1
  },
  {
    "id": "ref-29",
    "number": 29,
    "category": "sources",
    "title": "习近平在正定",
    "author": "中央党校采访实录编辑室",
    "source": "用户文档尾注",
    "date": "见原始著录",
    "kind": "M",
    "theme": "人物经历",
    "keywords": [
      "中央党校采访实录编辑室",
      "M",
      "出版信息可核",
      "未逐句核对"
    ],
    "demo": false,
    "art": "document",
    "summary": "正文引用 1 处 · 出版信息可核",
    "body": "人民网图书简介可核书名、编写者及2019年出版信息；具体页码待补。",
    "url": null,
    "alternativeUrl": "https://theory.people.com.cn/n1/2019/0617/c427900-31156256.html",
    "verified": "出版信息可核",
    "claimStatus": "未逐句核对",
    "claimNote": "本轮只核对了来源或著录信息，未将正文所有事实逐句与原文比对。",
    "bibliography": "中央党校采访实录编辑室. 习近平在正定[M]. 北京: 中共中央党校出版社, 2019.",
    "citedParagraphs": [
      224
    ],
    "citationCount": 1
  }
];
